version: "3.9"
services:
  oidc:
    image: "oidc_provider:latest"
    build:
      context: ./oidc
    ports:
      - "3000:3000"
    env_file:
      - ./oidc/.secret.env
    environment:
      - CLIENTS_CONFIG=/home/oidcrunner/config/clients.yml
      - ISSUER=http://${LOCALHOST}:3000
      - CLIENT_HOST=${LOCALHOST}
    volumes:
      - ${PWD}/oidc/clients.yml:/home/oidcrunner/config/clients.yml
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/.well-known/openid-configuration']
      start_period: 2s
    extra_hosts:
      - "${LOCALHOST}:host-gateway"
  api:
    image: "react-api:latest"
    build:
      context: ./api
    ports:
      - "5556:5556"
    environment:
      - OIDC_PROVIDER_URI=http://${LOCALHOST}:3000
      - HOSTNAME=api
      - PORT=5556
      - CLIENT_AUDIENCE=node_client
    depends_on:
      oidc:
        condition: service_healthy
    extra_hosts:
      - "${LOCALHOST}:host-gateway"
  ui:
    image: "react-ui:latest"
    build:
      context: ./ui-next
    ports:
      - "3001:3001"
    environment:
      - SERVER_API_BASE_URI=http://api:5556
      - LOCAL_OIDC_WELL_KNOWN=http://${LOCALHOST}:3000/.well-known/openid-configuration
      - NEXTAUTH_URL=http://localhost:3001
      - NEXTAUTH_URL_INTERNAL=http://oidc:3001/
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - LOCAL_OIDC_CLIENT_SECRET=${LOCAL_OIDC_CLIENT_SECRET}
    depends_on:
      oidc:
        condition: service_healthy
    extra_hosts:
      - "${LOCALHOST}:host-gateway"
