version: "3.9"
services:
  oidc:
    image: "oidc_provider:latest"
    build:
      context: ./oidc
    ports:
      - "3000:3000"
    env_file:
      - ./oidc/.secret.env
    environment:
      - CLIENTS_CONFIG=/home/oidcrunner/config/clients.yml
      - ISSUER=http://${LOCALHOST}:3000
      - CLIENT_HOST=${LOCALHOST}
    volumes:
      - ${PWD}/oidc/clients.yml:/home/oidcrunner/config/clients.yml
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/.well-known/openid-configuration']
      start_period: 5s
    extra_hosts:
      - "${LOCALHOST}:host-gateway"
  api:
    image: "react-api:latest"
    build:
      context: ./api
    ports:
      - "5556:5556"
    environment:
      - CLIENT_ID=oidc_client
      - OIDC_PROVIDER_URI=http://${LOCALHOST}:3000
      - HOSTNAME=api
      - PORT=5556
      - REDIRECT_URI=http://${LOCALHOST}:5556
    env_file:
      - ./api/.secret.env
    depends_on:
      oidc:
        condition: service_healthy
    extra_hosts:
      - "${LOCALHOST}:host-gateway"
